# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            local:
                directory: '%kernel.project_dir%/var/storage/default'
        avatars.storage:
            local:
                directory: '%kernel.project_dir%/public/%app.avatar.path%'

when@test:
    flysystem:
        storages:
            avatars.storage:
                local:
                    directory: '%kernel.project_dir%/var/test/uploads/avatars'
