twig:
    file_name_pattern: '*.twig'
    globals:
        mapbox_public_api_key: '%env(string:MAPBOX_PUBLIC_TOKEN)%'
    form_themes:
        - 'form/tailwind_shadcn_theme.html.twig'

when@test:
    twig:
        strict_variables: true
