sonar.projectKey=surf-trip
sonar.projectName=Surf Trip
sonar.projectVersion=1.0

sonar.host.url=http://host.docker.internal:9002

sonar.links.homepage=https://github.com/RomMad/surf-trip
sonar.links.ci=https://github.com/RomMad/surf-trip/actions/workflows/ci.yaml?query=workflow%3ACI
sonar.links.issue=https://github.com/RomMad/surf-trip/issues

sonar.sources=src,assets,templates
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=var/test-reports/phpunit-coverage-result.xml
sonar.php.phpstan.reportPaths=var/test-reports/phpstan-report.json
sonar.php.tests.reportPath=var/test-reports/phpunit-report.xml

sonar.exclusions=\
vendor/**,\
var/**,\
public/build/**,\
node_modules/**,\
migrations/**
