<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260515135212 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create surf_session table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE surf_session (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            board VARCHAR(100) DEFAULT NULL,
            spot VARCHAR(100) NOT NULL,
            start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            end_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            rating SMALLINT DEFAULT NULL,
            objective TEXT DEFAULT NULL,
            comment TEXT DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');

        $this->addSql('ALTER TABLE surf_session ADD CONSTRAINT FK_BB9F2D91A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_BB9F2D91A76ED395 ON surf_session (user_id)');
        $this->addSql('CREATE INDEX idx_surf_session_start_at ON surf_session (start_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE surf_session DROP CONSTRAINT FK_BB9F2D91A76ED395');
        $this->addSql('DROP INDEX IDX_BB9F2D91A76ED395');

        $this->addSql('DROP TABLE surf_session');
    }
}
